repo_root: "../../"
test_command: "./mvnw -q -Dtest=ContractTests test"
surefire_dir: "target/surefire-reports"
specmatic_log: "specmatic.log"
spec_keyword: "openapi"
specmatic_config: "specmatic.yaml"

ollama:
  base_url: "http://localhost:11434"
  planner_model: "llama3.1"          # for summaries/plans
  coder_model: "qwen2.5-coder"       # for code/spec diffs
  critic_model: "llama3.1"

limits:
  files_per_section: 6              # cap on files read for context
  max_context_chars: 12000              # guardrails

output_dir: "tools/out/.agentic"
